server:
  port: 2222
  mode: "dev"
redis:
  host: redis
  port: 6379
  password:
  database: 0
mysql:
  host: mysql
  port: 3306
  username: root
  password: root
  dbname: shopdevgo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
log:
  log_level: debug
  file_log_name: "./storage/logs/log.001.log"
  max_size: 500
  max_backup: 3
  max_age: 28
  compress: true